# Generated by Django 3.2.6 on 2021-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_auto_20211008_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='categorytime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='is_approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='is_reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
