# Generated by Django 3.2.6 on 2021-10-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_auto_20211015_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='status',
        ),
    ]
